service: python-lambda-sandbox

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  stage: dev
  region: ca-central-1

functions:
  basicFunction:
    handler: lambda/basic_function.handler
    events:
      - http:
          path: basic-function
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
